name: Build Kernel

on:
  watch:
    types: [started]
  workflow_dispatch:
 
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: Abdelhay-Ali/android_kernel_huawei_hi6250_KernelSU@main 
      id: build
      env:
        NAME: Dark-Ages-Último
      with:
        arch: arm64
        compiler: gcc/9
        defconfig: p20_defconfig
        image: Image.gz-dtb
        
    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v4.0.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        #artifacts: "kernel_huawei_hi6250_4.9.319/artifacts/${{ steps.build.outputs.outfile }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
